### ISSUE TITLE
Support for LocalStoreServerCertificateSource Find by value/type

### ISSUE THREAD

**Issue by edinmilic** [mataness/Kestrel.HttpsCertificateSelection#3]
Can you please add support for finding the certificate in the local store by value and findtype, and not just by subject name?

It is beneficial to be able to locate the certificate by something other than subject name in most scenarios. Subject name lookup right now does a FindBySubjectName and the recommendation is to use FindBySubjectDistinguishedName because it is a more specific search https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509findtype?view=net-8.0

**Comment by mataness** [comment]
I agree.
Would you like to contribute this functionality?
1. Add 'FindType' to [ServerLocalCertificateStoreConfigurationOptions ](https://github.com/mataness/Kestrel.HttpsCertificateSelection/blob/main/Kestrel.HttpsCertificateSelection/CertificateSelection/Configuration/ServerLocalCertificateStoreConfigurationOptions.cs) with default value of FindBySubjectName
2. Add 'FindType' as another input parameter for  [LocalStoreServerCertificateSource ](https://github.com/mataness/Kestrel.HttpsCertificateSelection/blob/main/Kestrel.HttpsCertificateSelection/CertificateSelection/LocalStore/LocalStoreServerCertificateSource.cs) and implement the needed logic
3. Pass FindType in ConfigureLocalStoreServerCertificateSelection to LocalStoreServerCertificateSource  https://github.com/mataness/Kestrel.HttpsCertificateSelection/blob/main/Kestrel.HttpsCertificateSelection/HttpsConnectionAdapterOptionsExtensions.cs

**Comment by edinmilic** [comment]
Yes, if you can grant the permission I can have a PR

**Comment by mataness** [comment]
Permissions for what? fork the repo and submit a PR

**Comment by mataness** [comment]
https://github.com/mataness/Kestrel.HttpsCertificateSelection/pull/4

**Comment by mataness** [comment]
v2 released to public feed
